from __future__ import annotations

"""Sensor and device templates for Lambda Heat Pumps integration."""

# Sensor Templates

# Heat Pump Sensors
HP_SENSOR_TEMPLATES = {
    "error_state": {
        "relative_address": 0,
        "name": "Error State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "txt_mapping": True,
        "options": {"register": True},
    },
    "error_number": {
        "relative_address": 1,
        "name": "Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total",
    },
    "state": {
        "relative_address": 2,
        "name": "State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "txt_mapping": True,
        "options": {"register": True},
    },
    "operating_state": {
        "relative_address": 3,
        "name": "Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "txt_mapping": True,
        "options": {"register": True},
    },
    "flow_line_temperature": {
        "relative_address": 4,
        "name": "Flow Line Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "return_line_temperature": {
        "relative_address": 5,
        "name": "Return Line Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "volume_flow_heat_sink": {
        "relative_address": 6,
        "name": "Volume Flow Heat Sink",
        "unit": "l/h",
        "scale": 1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total",
    },
    "energy_source_inlet_temperature": {
        "relative_address": 7,
        "name": "Energy Source Inlet Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "energy_source_outlet_temperature": {
        "relative_address": 8,
        "name": "Energy Source Outlet Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "volume_flow_energy_source": {
        "relative_address": 9,
        "name": "Volume Flow Energy Source",
        "unit": "l/min",
        "scale": 0.01,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total",
    },
    "compressor_unit_rating": {
        "relative_address": 10,
        "name": "Compressor Unit Rating",
        "unit": "%",
        "scale": 0.01,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total",
    },
    "actual_heating_capacity": {
        "relative_address": 11,
        "name": "Actual Heating Capacity",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "inverter_power_consumption": {
        "relative_address": 12,
        "name": "Inverter Power Consumption",
        "unit": "W",
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "cop": {
        "relative_address": 13,
        "name": "COP",
        "unit": None,
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total",
    },
    "request_type": {
        "relative_address": 15,
        "name": "Request-Type",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "total",
    },
    "requested_flow_line_temperature": {
        "relative_address": 16,
        "name": "Requested Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "requested_return_line_temperature": {
        "relative_address": 17,
        "name": "Requested Return Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "requested_flow_to_return_line_temperature_difference": {
        "relative_address": 18,
        "name": "Requested Flow to Return Line Temperature Difference",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "relais_state_2nd_heating_stage": {
        "relative_address": 19,
        "name": "Relais State 2nd Heating Stage",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "txt_mapping": True,
    },
    "compressor_power_consumption_accumulated": {
        "relative_address": 20,
        "name": "Compressor Power Consumption Accumulated",
        "unit": "Wh",
        "scale": 1,
        "precision": 0,
        "data_type": "int32",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
    },
    "compressor_thermal_energy_output_accumulated": {
        "relative_address": 22,
        "name": "Compressor Thermal Energy Output Accumulated",
        "unit": "Wh",
        "scale": 1,
        "precision": 0,
        "data_type": "int32",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
    },
    # Undocumented registers discovered on hardware - Always enabled
    "config_parameter_24": {
        "relative_address": 24,
        "name": "Unknown Parameter (R1024)",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
    "vda_rating": {
        "relative_address": 25,
        "name": "VdA Rating",
        "unit": "%",
        "scale": 0.01,
        "precision": 2,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
    "hot_gas_temperature": {
        "relative_address": 26,
        "name": "Hot Gas Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "subcooling_temperature": {
        "relative_address": 27,
        "name": "Subcooling Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "suction_gas_temperature": {
        "relative_address": 28,
        "name": "Suction Gas Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "condensation_temperature": {
        "relative_address": 29,
        "name": "Condensation Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "evaporation_temperature": {
        "relative_address": 30,
        "name": "Evaporation Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 2,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "eqm_rating": {
        "relative_address": 31,
        "name": "EqM Rating",
        "unit": "%",
        "scale": 0.01,
        "precision": 2,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
    "expansion_valve_opening_angle": {
        "relative_address": 32,
        "name": "Expansion Valve Opening Angle",
        "unit": "%",
        "scale": 0.01,
        "precision": 2,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
     "config_parameter_33": {
        "relative_address": 33,
        "name": "Unknown Parameter (R1033)",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },   
    "config_parameter_50": {
        "relative_address": 50,
        "name": "Unknown Parameter (R1050)",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
    "dhw_output_power_15c": {
        "relative_address": 51,
        "name": "DHW Output Power at 15°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_min_output_power_15c": {
        "relative_address": 52,
        "name": "Heating Min Output Power at 15°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_max_output_power_15c": {
        "relative_address": 53,
        "name": "Heating Max Output Power at 15°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_min_output_power_0c": {
        "relative_address": 54,
        "name": "Heating Min Output Power at 0°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_max_output_power_0c": {
        "relative_address": 55,
        "name": "Heating Max Output Power at 0°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_min_output_power_minus15c": {
        "relative_address": 56,
        "name": "Heating Min Output Power at -15°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "heating_max_output_power_minus15c": {
        "relative_address": 57,
        "name": "Heating Max Output Power at -15°C",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "cooling_min_output_power": {
        "relative_address": 58,
        "name": "Cooling Min Output Power",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "cooling_max_output_power": {
        "relative_address": 59,
        "name": "Cooling Max Output Power",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "power",
    },
    "config_parameter_60": {
        "relative_address": 60,
        "name": "Unknown Parameter (R1060)",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "Hp",
        "writeable": False,
        "state_class": "measurement",
    },
}

# Boiler Sensors
BOIL_SENSOR_TEMPLATES = {
    "error_number": {
        "relative_address": 0,
        "name": "Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "state_class": "total",
    },
    "operating_state": {
        "relative_address": 1,
        "name": "Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "txt_mapping": True,
        "options": {"register": True},
    },
    "actual_high_temperature": {
        "relative_address": 2,
        "name": "Actual High Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "actual_low_temperature": {
        "relative_address": 3,
        "name": "Actual Low Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "target_high_temperature": {
        "relative_address": 50,
        "name": "Target High Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "actual_circulation_temperature": {
        "relative_address": 4,
        "name": "Actual Circulation Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "actual_circulation_pump_state": {
        "relative_address": 5,
        "name": "Circulation Pump State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": False,
        "txt_mapping": True,
    },
    # "maximum_boiler_temperature": {
    #     "relative_address": 50,
    #     "name": "Maximum Temperature",
    #     "unit": "°C",
    #     "scale": 0.1,
    #     "precision": 1,
    #     "data_type": "int16",
    #     "firmware_version": 1,
    #     "device_type": "boil",
    #     "writeable": True,
    #     "state_class": "measurement",
    #     "device_class": "temperature",
    # },
    
}

# Buffer Sensors
BUFF_SENSOR_TEMPLATES = {
    "error_number": {
        "relative_address": 0,
        "name": "Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "total",
    },
    "operating_state": {
        "relative_address": 1,
        "name": "Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "txt_mapping": True,
    },
    "actual_high_temperature": {
        "relative_address": 2,
        "name": "Actual High Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "actual_low_temperature": {
        "relative_address": 3,
        "name": "Actual Low Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "buffer_temperature_high_setpoint": {
        "relative_address": 4,
        "name": "Buffer High Temperature Setpoint",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "request_type": {
        "relative_address": 5,
        "name": "Request Type",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "txt_mapping": True,
    },
    "request_flow_line_temp_setpoint": {
        "relative_address": 6,
        "name": "Flow Line Temperature Setpoint",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "request_return_line_temp_setpoint": {
        "relative_address": 7,
        "name": "Return Line Temperature Setpoint",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "request_heat_sink_temp_diff_setpoint": {
        "relative_address": 8,
        "name": "Heat Sink Temperature Difference Setpoint",
        "unit": "K",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
    },
    "modbus_request_heating_capacity": {
        "relative_address": 9,
        "name": "Requested Heating Capacity",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "maximum_buffer_temp": {
        "relative_address": 50,
        "name": "Maximum Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "buff",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
}

# Solar Sensors
SOL_SENSOR_TEMPLATES = {
    "error_number": {
        "relative_address": 0,
        "name": "Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "state_class": "total",
    },
    "operating_state": {
        "relative_address": 1,
        "name": "Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "txt_mapping": True,
    },
    "collector_temperature": {
        "relative_address": 2,
        "name": "Collector Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "storage_temperature": {
        "relative_address": 3,
        "name": "Storage Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "power_current": {
        "relative_address": 4,
        "name": "Power Current",
        "unit": "kW",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "energy_total": {
        "relative_address": 5,
        "name": "Energy Total",
        "unit": "kWh",
        "scale": 1,
        "precision": 0,
        "data_type": "int32",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
    },
    "maximum_buffer_temperature": {
        "relative_address": 50,
        "name": "Maximum Buffer Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "buffer_changeover_temperature": {
        "relative_address": 51,
        "name": "Buffer Changeover Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "sol",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
}

# Heating Circuit Sensors
HC_SENSOR_TEMPLATES = {
    "error_number": {
        "relative_address": 0,
        "name": "Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": False,
        "state_class": "total",
    },
    "operating_state": {
        "relative_address": 1,
        "name": "Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": False,
        "txt_mapping": True,
    },
    "flow_line_temperature": {
        "relative_address": 2,
        "name": "Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "return_line_temperature": {
        "relative_address": 3,
        "name": "Return Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "room_device_temperature": {
        "relative_address": 4,
        "name": "Room Device Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "set_flow_line_temperature": {
        "relative_address": 5,
        "name": "Set Flow Line Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "operating_mode": {
        "relative_address": 6,
        "name": "Operating Mode",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "txt_mapping": True,
    },
    "flow_line_temperature_setpoint": {
        "relative_address": 7,
        "name": "Flow Line Temperature Setpoint",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "set_flow_line_offset_temperature": {
        "relative_address": 50,
        "name": "Set Flow Line Offset Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "target_room_temperature": {
        "relative_address": 51,
        "name": "Target Room Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "set_cooling_mode_room_temperature": {
        "relative_address": 52,
        "name": "Set Cooling Mode Room Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "state_class": "measurement",
        "device_class": "temperature",
    },
     "target_temp_flow_line": {
         "relative_address": 7,
         "name": "Target Flow Line Temperature",
         "unit": "°C",
         "scale": 0.1,
         "precision": 1,
         "data_type": "int16",
         "firmware_version": 3,
         "device_type": "hc",
         "writeable": False,
         "state_class": "measurement",
         "device_class": "temperature",
     },
}

HC_HEATING_CURVE_NUMBER_CONFIG = {
    "heating_curve_cold_outside_temp": {
        "name": "Heating Curve Cold Outside Temp",
        "default": 48.3,
        "min_value": 15.0,
        "max_value": 75.0,
        "step": 0.1,
        "unit": "°C",
        "outside_temp_point": -22.0,
        "icon": "mdi:chart-bell-curve-cumulative",
    },
    "heating_curve_mid_outside_temp": {
        "name": "Heating Curve Mid Outside Temp",
        "default": 39.0,
        "min_value": 15.0,
        "max_value": 75.0,
        "step": 0.1,
        "unit": "°C",
        "outside_temp_point": 0.0,
        "icon": "mdi:chart-bell-curve-cumulative",
    },
    "heating_curve_warm_outside_temp": {
        "name": "Heating Curve Warm Outside Temp",
        "default": 32.0,
        "min_value": 15.0,
        "max_value": 75.0,
        "step": 0.1,
        "unit": "°C",
        "outside_temp_point": 22.0,
        "icon": "mdi:chart-bell-curve-cumulative",
    },
}

HC_ROOM_THERMOSTAT_NUMBER_CONFIG = {
    "room_thermostat_offset": {
        "name": "Room Thermostat Offset",
        "default": 0.0,
        "min_value": -10.0,
        "max_value": 10.0,
        "step": 0.1,
        "precision": 1,
        "unit": "°C",
        "icon": "mdi:thermometer-lines",
    },
    "room_thermostat_factor": {
        "name": "Room Thermostat Factor",
        "default": 1.0,
        "min_value": 1.0,
        "max_value": 5.0,
        "step": 0.1,
        "precision": 1,
        "icon": "mdi:plus-minus",
    },
}

HC_FLOW_LINE_OFFSET_NUMBER_CONFIG = {
    "flow_line_offset_temperature": {
        "name": "Flow Line Offset Temperature",
        "default": 0.0,
        "min_value": -10.0,
        "max_value": 10.0,
        "step": 0.1,
        "precision": 1,
        "unit": "°C",
        "icon": "mdi:thermometer-adjust",
        "relative_address": 50,  # Aus HC_SENSOR_TEMPLATES
        "scale": 0.1,  # Für Modbus-Konvertierung
    },
}

HC_ECO_TEMP_REDUCTION_NUMBER_CONFIG = {
    "eco_temp_reduction": {
        "name": "Eco Temperature Reduction",
        "default": -1.0,
        "min_value": -10.0,
        "max_value": 0.0,
        "step": 0.1,
        "precision": 1,
        "unit": "°C",
        "icon": "mdi:thermometer-minus",
    },
}

HC_HEATING_CURVE_TEMPLATE_PARAMS = {
    "ambient_sensor": "sensor.ambient_temperature_calculated",
    "cold_point": HC_HEATING_CURVE_NUMBER_CONFIG["heating_curve_cold_outside_temp"][
        "outside_temp_point"
    ],
    "mid_point": HC_HEATING_CURVE_NUMBER_CONFIG["heating_curve_mid_outside_temp"][
        "outside_temp_point"
    ],
    "warm_point": HC_HEATING_CURVE_NUMBER_CONFIG["heating_curve_warm_outside_temp"][
        "outside_temp_point"
    ],
    "default_cold": HC_HEATING_CURVE_NUMBER_CONFIG["heating_curve_cold_outside_temp"][
        "default"
    ],
    "default_mid": HC_HEATING_CURVE_NUMBER_CONFIG["heating_curve_mid_outside_temp"][
        "default"
    ],
    "default_warm": HC_HEATING_CURVE_NUMBER_CONFIG[
        "heating_curve_warm_outside_temp"
    ]["default"],
    "supports_room_thermostat": True,
}

# General Sensors
SENSOR_TYPES = {
    # General Ambient
    "ambient_error_number": {
        "address": 0,
        "name": "Ambient Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "total",
        "options": {"register": True},
    },
    "ambient_operating_state": {
        "address": 1,
        "name": "Ambient Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "txt_mapping": True,
        "options": {"register": True},
    },
    "ambient_temperature": {
        "address": 2,
        "name": "Ambient Temperature",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "ambient_temperature_1h": {
        "address": 3,
        "name": "Ambient Temperature 1h",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "ambient_temperature_calculated": {
        "address": 4,
        "name": "Ambient Temperature Calculated",
        "unit": "°C",
        "scale": 0.1,
        "precision": 1,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "temperature",
    },
    "emgr_error_number": {
        "address": 100,
        "name": "E-Manager Error Number",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "total",
    },
    "emgr_operating_state": {
        "address": 101,
        "name": "E-Manager Operating State",
        "unit": None,
        "scale": 1,
        "precision": 0,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "txt_mapping": True,
    },
    "emgr_actual_power": {
        "address": 102,
        "name": "E-Manager Actual Power",
        "unit": "W",
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "emgr_actual_power_consumption": {
        "address": 103,
        "name": "E-Manager Power Consumption",
        "unit": "W",
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },
    "emgr_power_consumption_setpoint": {
        "address": 104,
        "name": "E-Manager Power Consumption Setpoint",
        "unit": "W",
        "scale": 1,
        "precision": 0,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "main",
        "writeable": False,
        "state_class": "measurement",
        "device_class": "power",
    },

}

# Climate Sensors
CLIMATE_TEMPLATES = {
    "hot_water": {
        "relative_address": 2,
        "relative_set_address": 50,
        "name": "Hot Water",
        "unit": "°C",
        "scale": 0.1,
        "precision": 0.5,
        "data_type": "int16",
        "firmware_version": 1,
        "device_type": "boil",
        "writeable": True,
        "hvac_mode": {"heat"},
        "state_class": "measurement",
    },
    "heating_circuit": {
        "relative_address": 4,  # room_device_temperature
        "relative_set_address": 51,  # target_room_temperature
        "name": "Heating Circuit",
        "unit": "°C",
        "scale": 0.1,
        "precision": 0.1,
        "data_type": "uint16",
        "firmware_version": 1,
        "device_type": "hc",
        "writeable": True,
        "hvac_mode": {"heat"},
        "state_class": "measurement",
    },
}


# Energy Consumption Sensor Templates
ENERGY_CONSUMPTION_SENSOR_TEMPLATES = {
        # --- THERMAL ENERGY SENSORS (per HP, per mode, per period) ---
        # Heating
        "heating_thermal_energy_total": {
            "name": "Heating Thermal Energy Total",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "heating",
            "period": "total",
            "reset_interval": None,
            "description": "Thermal output total for heating in kWh",
        },
        "heating_thermal_energy_daily": {
            "name": "Heating Thermal Energy Daily",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "heating",
            "reset_interval": "daily",
            "description": "Thermal output daily for heating in kWh",
        },
        "heating_thermal_energy_monthly": {
            "name": "Heating Thermal Energy Monthly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "heating",
            "reset_interval": "monthly",
            "description": "Thermal output monthly for heating in kWh",
        },
        "heating_thermal_energy_yearly": {
            "name": "Heating Thermal Energy Yearly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "heating",
            "reset_interval": "yearly",
            "description": "Thermal output yearly for heating in kWh",
        },
        "heating_thermal_energy_hourly": {
            "name": "Heating Thermal Energy Hourly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "heating",
            "reset_interval": "hourly",
            "description": "Thermal output hourly for heating in kWh",
        },
        # Hot Water
        "hot_water_thermal_energy_total": {
            "name": "Hot Water Thermal Energy Total",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "hot_water",
            "period": "total",
            "reset_interval": None,
            "description": "Thermal output total for hot water in kWh",
        },
        "hot_water_thermal_energy_daily": {
            "name": "Hot Water Thermal Energy Daily",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "hot_water",
            "reset_interval": "daily",
            "description": "Thermal output daily for hot water in kWh",
        },
        "hot_water_thermal_energy_monthly": {
            "name": "Hot Water Thermal Energy Monthly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "hot_water",
            "reset_interval": "monthly",
            "description": "Thermal output monthly for hot water in kWh",
        },
        "hot_water_thermal_energy_yearly": {
            "name": "Hot Water Thermal Energy Yearly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "hot_water",
            "reset_interval": "yearly",
            "description": "Thermal output yearly for hot water in kWh",
        },
        # Cooling
        "cooling_thermal_energy_total": {
            "name": "Cooling Thermal Energy Total",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "cooling",
            "period": "total",
            "reset_interval": None,
            "description": "Thermal output total for cooling in kWh",
        },
        "cooling_thermal_energy_daily": {
            "name": "Cooling Thermal Energy Daily",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "cooling",
            "reset_interval": "daily",
            "description": "Thermal output daily for cooling in kWh",
        },
        "cooling_thermal_energy_monthly": {
            "name": "Cooling Thermal Energy Monthly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "cooling",
            "reset_interval": "monthly",
            "description": "Thermal output monthly for cooling in kWh",
        },
        "cooling_thermal_energy_yearly": {
            "name": "Cooling Thermal Energy Yearly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "cooling",
            "reset_interval": "yearly",
            "description": "Thermal output yearly for cooling in kWh",
        },
        # Defrost
        "defrost_thermal_energy_total": {
            "name": "Defrost Thermal Energy Total",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "defrost",
            "period": "total",
            "reset_interval": None,
            "description": "Thermal output total for defrost in kWh",
        },
        "defrost_thermal_energy_daily": {
            "name": "Defrost Thermal Energy Daily",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "defrost",
            "reset_interval": "daily",
            "description": "Thermal output daily for defrost in kWh",
        },
        "defrost_thermal_energy_monthly": {
            "name": "Defrost Thermal Energy Monthly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "defrost",
            "reset_interval": "monthly",
            "description": "Thermal output monthly for defrost in kWh",
        },
        "defrost_thermal_energy_yearly": {
            "name": "Defrost Thermal Energy Yearly",
            "unit": "kWh",
            "precision": 6,
            "data_type": "thermal_calculated",
            "firmware_version": 1,
            "device_type": "hp",
            "writeable": False,
            "state_class": "total",
            "device_class": "energy",
            "operating_state": "defrost",
            "reset_interval": "yearly",
            "description": "Thermal output yearly for defrost in kWh",
        },
    # Heating Energy Sensoren
    "heating_energy_total": {
        "name": "Heating Energy Total",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
        "mode_value": 1,  # CH
        "operating_state": "heating",
        "period": "total",
        "reset_interval": None,
        "description": "Gesamtverbrauch für Heizen in kWh",
    },
    "heating_energy_daily": {
        "name": "Heating Energy Daily",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "heating",
        "reset_interval": "daily",
        "description": "Täglicher Verbrauch für Heizen in kWh",
    },
    "heating_energy_hourly": {
        "name": "Heating Energy Hourly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "heating",
        "reset_interval": "hourly",
        "description": "Stündlicher Verbrauch für Heizen in kWh (Debug)",
    },
    # Hot Water Energy Sensoren
    "hot_water_energy_total": {
        "name": "Hot Water Energy Total",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
        "mode_value": 2,  # DHW
        "operating_state": "hot_water",
        "period": "total",
        "reset_interval": None,
        "description": "Gesamtverbrauch für Warmwasser in kWh",
    },
    "hot_water_energy_daily": {
        "name": "Hot Water Energy Daily",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "hot_water",
        "reset_interval": "daily",
        "description": "Täglicher Verbrauch für Warmwasser in kWh",
    },
    # Cooling Energy Sensoren
    "cooling_energy_total": {
        "name": "Cooling Energy Total",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
        "mode_value": 3,  # CC
        "operating_state": "cooling",
        "period": "total",
        "reset_interval": None,
        "description": "Gesamtverbrauch für Kühlen in kWh",
    },
    "cooling_energy_daily": {
        "name": "Cooling Energy Daily",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "cooling",
        "reset_interval": "daily",
        "description": "Täglicher Verbrauch für Kühlen in kWh",
    },
    # Defrost Energy Sensoren
    "defrost_energy_total": {
        "name": "Defrost Energy Total",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
        "mode_value": 5,  # DEFROST
        "operating_state": "defrost",
        "period": "total",
        "reset_interval": None,
        "description": "Gesamtverbrauch für Abtauen in kWh",
    },
    "defrost_energy_daily": {
        "name": "Defrost Energy Daily",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "defrost",
        "reset_interval": "daily",
        "description": "Täglicher Verbrauch für Abtauen in kWh",
    },
    # STBY Energy Sensoren
    "stby_energy_total": {
        "name": "STBY Energy Total",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total_increasing",
        "device_class": "energy",
        "operating_state": "stby",
        "period": "total",
        "reset_interval": None,
        "description": "Gesamtverbrauch für Standby in kWh",
    },
    "stby_energy_daily": {
        "name": "STBY Energy Daily",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "stby",
        "reset_interval": "daily",
        "description": "Täglicher Verbrauch für Standby in kWh",
    },
    # Monthly Energy Sensoren
    "heating_energy_monthly": {
        "name": "Heating Energy Monthly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "heating",
        "reset_interval": "monthly",
        "description": "Monatlicher Verbrauch für Heizen in kWh",
    },
    "hot_water_energy_monthly": {
        "name": "Hot Water Energy Monthly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "hot_water",
        "reset_interval": "monthly",
        "description": "Monatlicher Verbrauch für Warmwasser in kWh",
    },
    "cooling_energy_monthly": {
        "name": "Cooling Energy Monthly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "cooling",
        "reset_interval": "monthly",
        "description": "Monatlicher Verbrauch für Kühlen in kWh",
    },
    "defrost_energy_monthly": {
        "name": "Defrost Energy Monthly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "defrost",
        "reset_interval": "monthly",
        "description": "Monatlicher Verbrauch für Abtauen in kWh",
    },
    "stby_energy_monthly": {
        "name": "STBY Energy Monthly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "stby",
        "reset_interval": "monthly",
        "description": "Monatlicher Verbrauch für Standby in kWh",
    },
    # Yearly Energy Sensoren
    "heating_energy_yearly": {
        "name": "Heating Energy Yearly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "heating",
        "reset_interval": "yearly",
        "description": "Jährlicher Verbrauch für Heizen in kWh",
    },
    "hot_water_energy_yearly": {
        "name": "Hot Water Energy Yearly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "hot_water",
        "reset_interval": "yearly",
        "description": "Jährlicher Verbrauch für Warmwasser in kWh",
    },
    "cooling_energy_yearly": {
        "name": "Cooling Energy Yearly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "cooling",
        "reset_interval": "yearly",
        "description": "Jährlicher Verbrauch für Kühlen in kWh",
    },
    "defrost_energy_yearly": {
        "name": "Defrost Energy Yearly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "defrost",
        "reset_interval": "yearly",
        "description": "Jährlicher Verbrauch für Abtauen in kWh",
    },
    "stby_energy_yearly": {
        "name": "STBY Energy Yearly",
        "unit": "kWh",
        "precision": 6,
        "data_type": "calculated",
        "firmware_version": 1,
        "device_type": "hp",
        "writeable": False,
        "state_class": "total",
        "device_class": "energy",
        "operating_state": "stby",
        "reset_interval": "yearly",
        "description": "Jährlicher Verbrauch für Standby in kWh",
    },
}

# Legacy-Konstanten für Rückwärtskompatibilität - Direkt aus Templates berechnet
ENERGY_CONSUMPTION_MODES = sorted(list(set(
    template["operating_state"] 
    for template in ENERGY_CONSUMPTION_SENSOR_TEMPLATES.values()
    if "operating_state" in template
)))

ENERGY_CONSUMPTION_PERIODS = sorted(list(set(
    template["period"] if "period" in template 
    else template["reset_interval"] 
    for template in ENERGY_CONSUMPTION_SENSOR_TEMPLATES.values()
    if "period" in template or (template.get("reset_interval") is not None)
) | {"monthly", "yearly"}))

